config/routes.rb
Rails.application.routes.draw do
  resources :weight_calculators
  resources :charts do
    get :download_report
  end
  resources :trackers

  scope :ujs, defaults: { format: :ujs } do
    patch 'wt_totals' => 'weight_calculators#totals'
    patch 'thing_totals' => 'trackers#totals'
  end
  post 'search' => 'trackers#search'
  resources :import  do
    collection do
      post :import
      post :parts
    end
  end
  resources :iot_data do
      get :process_start
      get :download_report
    
    collection do
      post :import
    end
  end
  
  devise_for :users, only: :session, path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :users, only: [:show]
  root to: 'visitors#index'
end

app/models/weight_calculator.rb
class WeightCalculator < ActiveRecord::Base
end

app/controllers/weight_calculators_controller.rb
class WeightCalculatorsController < ApplicationController
  include ActionView::Helpers::NumberHelper
  protect_from_forgery :except => :totals
  before_action :set_weight_calculator, only: [:show, :edit, :update, :destroy]

  # GET /weight_calculators
  # GET /weight_calculators.json
  def index
    @weight_calculators = WeightCalculator.all
  end

  def totals
    weight_per_part = params[:wpp]
    count = params[:count]

    if weight_per_part && count
      value = number_with_precision((weight_per_part.to_f * count.to_f), :precision => 2)
    else
      value = 0.00
    end
    render js: "$('#dashboard-totals').html('#{value} Kgs')"
  end

  # GET /weight_calculators/1
  # GET /weight_calculators/1.json
  def show
  end

  # GET /weight_calculators/new
  def new
    @weight_calculator = WeightCalculator.new
  end

  # GET /weight_calculators/1/edit
  def edit
  end

  # POST /weight_calculators
  # POST /weight_calculators.json
  def create
    @weight_calculator = WeightCalculator.new(weight_calculator_params)

    respond_to do |format|
      if @weight_calculator.save
        format.html { redirect_to @weight_calculator, notice: 'Weight calculator was successfully created.' }
        format.json { render :show, status: :created, location: @weight_calculator }
      else
        format.html { render :new }
        format.json { render json: @weight_calculator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weight_calculators/1
  # PATCH/PUT /weight_calculators/1.json
  def update
    respond_to do |format|
      if @weight_calculator.update(weight_calculator_params)
        format.html { redirect_to @weight_calculator, notice: 'Weight calculator was successfully updated.' }
        format.json { render :show, status: :ok, location: @weight_calculator }
      else
        format.html { render :edit }
        format.json { render json: @weight_calculator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weight_calculators/1
  # DELETE /weight_calculators/1.json
  def destroy
    @weight_calculator.destroy
    respond_to do |format|
      format.html { redirect_to weight_calculators_url, notice: 'Weight calculator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight_calculator
      @weight_calculator = WeightCalculator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weight_calculator_params
      params.require(:weight_calculator).permit(:part_code, :wpp, :count, :idm, :mpq)
    end
end

app/helpers/weight_calculators_helper.rb
module WeightCalculatorsHelper
end

app/views/weight_calculators/_form.html.erb
<%= form_for(@weight_calculator) do |f| %>
  <% if @weight_calculator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weight_calculator.errors.count, "error") %> prohibited this weight_calculator from being saved:</h2>

      <ul>
      <% @weight_calculator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :part_code %><br>
    <%= f.text_field :part_code %>
  </div>
  <div class="field">
    <%= f.label :wpp %><br>
    <%= f.text_field :wpp %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.text_field :count %>
  </div>
  <div class="field">
    <%= f.label :idm %><br>
    <%= f.number_field :idm %>
  </div>
  <div class="field">
    <%= f.label :mpq %><br>
    <%= f.text_field :mpq %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weight_calculators/edit.html.erb
<h1>Editing Weight Calculator</h1>

<%= render 'form' %>

<%= link_to 'Show', @weight_calculator %> |
<%= link_to 'Back', weight_calculators_path %>

app/views/weight_calculators/index.html.erb
<p id="notice"><%= notice %></p>

<% content_for :panel_heading do %>Weight Calculator
<% end %>

<div class="container">
  <div class='col-md-5' style="width: 23.666667%;">
    <div class="form-group">
      <%= form_tag wt_totals_path,method: :patch, remote: true  do %>
       <div class='input-group date' id='datetimepicker6'>
        <input id="fromdate" type='text' value="" name="wpp" class="form-control" placeholder="Per Part Weight">
        </div><br>
        <div class='input-group date' id='datetimepicker7'>
        <input id="todate" type='text' value="" name="count" class="form-control" placeholder="No. of Parts">
        </div><br>
       <span><%= submit_tag 'Calculate Weight', class: 'btn btn-success' %></span> 
      <% end %>         
      </div>
    </div>
    <div id="dashboard-totals" style="font-size: -webkit-xxx-large;color: darkblue;font-style: italic;"></div>
  </div>
</div> 

app/views/weight_calculators/new.html.erb
<h1>New Weight Calculator</h1>

<%= render 'form' %>

<%= link_to 'Back', weight_calculators_path %>

app/views/weight_calculators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Part code:</strong>
  <%= @weight_calculator.part_code %>
</p>

<p>
  <strong>Wpp:</strong>
  <%= @weight_calculator.wpp %>
</p>

<p>
  <strong>Count:</strong>
  <%= @weight_calculator.count %>
</p>

<p>
  <strong>Idm:</strong>
  <%= @weight_calculator.idm %>
</p>

<p>
  <strong>Mpq:</strong>
  <%= @weight_calculator.mpq %>
</p>

<%= link_to 'Edit', edit_weight_calculator_path(@weight_calculator) %> |
<%= link_to 'Back', weight_calculators_path %>