config/routes.rb
Rails.application.routes.draw do
  resources :weight_calculators
  resources :charts do
    get :download_report
  end
  resources :trackers

  scope :ujs, defaults: { format: :ujs } do
    patch 'wt_totals' => 'weight_calculators#totals'
    patch 'thing_totals' => 'trackers#totals'
  end
  post 'search' => 'trackers#search'
  resources :import  do
    collection do
      post :import
      post :parts
    end
  end
  resources :iot_data do
      get :process_start
      get :download_report
    
    collection do
      post :import
    end
  end
  
  devise_for :users, only: :session, path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :users, only: [:show]
  root to: 'visitors#index'
end

app/models/chart.rb
require 'csv'

class Chart < ActiveRecord::Base
	belongs_to :IotDatum
	belongs_to :WorkbenchMaster

  def self.to_csv
    attributes = %w{dates day_name workbench shift actual target progress}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |ds|
        csv << attributes.map{ |ds| user.send(attr) }
      end
    end
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:show, :edit, :update, :destroy]

  def index
    @charts = Chart.all
    @iot_data_for_1 = IotDatum.where("status = ? and count > ? and device_id = ?", 'Processing', 0, 1)
    @iot_data_for_2 = IotDatum.where("status = ? and count > ? and device_id = ?", 'Processing', 0, 2)
    
    @data_for_1 = []
    @data_for_2 = []
    @iot_data_for_1.each do |d|
      @data_for_1 << d.count
      @data_for_1 << d.target
      @data_for_1 << d.device_id
    end
    @iot_data_for_2.each do |f|
      @data_for_2 << f.count
      @data_for_2 << f.target
      @data_for_2 << f.device_id
    end

    @trackers_data_1 = Tracker.where("device_id = ?",1)
    @tracker_data_for_one = []
    @trackers_data_1.each do |one|
      @tracker_data_for_one << one.count
    end
    @trackers_data_2 = Tracker.where("device_id = ?",2)
    @tracker_data_for_two = []
    @trackers_data_1.each do |two|
      @tracker_data_for_two << two.count
    end

    adapt = ActiveRecord::Base.connection_config
    adapt = adapt.to_a
    puts adapt[0][1]

    if adapt[0][1] == 'mysql2'
      
    else
    # For PostgreSQL
      @day_wise = IotDatum.select("to_char(created_at, 'DD-MM-YYYY') as dates, to_char(created_at, 'Day') as day_name, sum(count) as actual, sum(target) as target, ROUND(((sum(count)::decimal/sum(target)::decimal) * 100),2) as progress").group("to_char(created_at, 'Day'), to_char(created_at, 'DD-MM-YYYY')")
      @@ds_wise = IotDatum.select("to_char(created_at, 'DD-MM-YYYY') as dates, to_char(created_at, 'Day') as day_name, device_id as workbench, shift, sum(target) as target, sum(count) as count, to_char(sum((updated_at - created_at)),'HH24:MI:SS') AS duration").where("status = 'Process Completed'").group("to_char(created_at, 'Day'), to_char(created_at, 'DD-MM-YYYY'), device_id, shift").order("to_char(created_at, 'DD-MM-YYYY')")
      @ds_wise = @@ds_wise
      @@sp_wise = IotDatum.select("to_char(created_at, 'DD-MM-YYYY') as dates, shift, device_id as workbench, part_number, to_char(sum((updated_at - created_at)),'HH24:MI:SS') AS duration").where("status = 'Process Completed'").group("part_number,shift,device_id,to_char(created_at, 'DD-MM-YYYY')").order("part_number")
      @sp_wise = @@sp_wise
      
      @weekly = IotDatum.select("extract(WEEK from created_at)::bigint as week_no, to_char(created_at, 'DD-MM-YYYY') as dates,to_char(created_at, 'Day') as day_name,sum(count) as actual, sum(target) as target, ROUND(((sum(count)::decimal/sum(target)::decimal) * 100),2) as progress").group("extract(WEEK from created_at),to_char(created_at, 'Day'),to_char(created_at, 'DD-MM-YYYY')")
      @monthly = IotDatum.select("to_char(created_at, 'Month') as month_name, sum(count) as actual, sum(target) as target, ROUND(((sum(count)::decimal/sum(target)::decimal) * 100),2) as progress").group("to_char(created_at, 'Month')")
      @yearly = IotDatum.select("extract(YEAR from created_at)::bigint as year_name, sum(count) as actual, sum(target) as target, ROUND(((sum(count)::decimal/sum(target)::decimal) * 100),2) as progress").group("extract(YEAR from created_at)")
    end

    @lb_result_cmp = IotDatum.select("employee_name, workbench_number, part_number, status, count, ROW_NUMBER() OVER (PARTITION BY status order by count desc)").where("status = 'Process Completed'").limit(5)
    @lb_result_pro = IotDatum.select("employee_name, workbench_number, part_number, status, target, count, RANK() OVER (PARTITION BY status order by count desc)").where("status = 'Processing'")
  end

  def download_report
    puts params[:chart_id]
    
    respond_to do |format|
      report_id = params[:chart_id]
      if report_id == 'ds'
        format.csv { send_data @@ds_wise.to_ds_csv, filename: "device_wise_report-#{Date.today}.csv" }
      elsif report_id == 'sp' 
        format.csv { send_data @@sp_wise.to_sp_csv, filename: "part_wise_report-#{Date.today}.csv" }
      end
    end
  end

  
  def show
  end

  
  def new
    @chart = Chart.new
  end

  
  def edit
  end

  
  def create
    @chart = Chart.new(chart_params)

    respond_to do |format|
      if @chart.save
        format.html { redirect_to @chart, notice: 'Chart was successfully created.' }
        format.json { render :show, status: :created, location: @chart }
      else
        format.html { render :new }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @chart.update(chart_params)
        format.html { redirect_to @chart, notice: 'Chart was successfully updated.' }
        format.json { render :show, status: :ok, location: @chart }
      else
        format.html { render :edit }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @chart.destroy
    respond_to do |format|
      format.html { redirect_to charts_url, notice: 'Chart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chart
      @chart = Chart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chart_params
      params.require(:chart).permit(:name)
    end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/_boards.html.erb
<style type="text/css">
  .col-lg-3 {
    width: 33%;
    font-size: 20px;
}
</style>
<!-- /.row -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                  <i class="fa fa-bullseye fa-3x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">
                                      <% @yearly.each do |pr| %>
                                        <%= pr.target %>
                                      <% end %>
                                    </div>
                                    <div>Target</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                  <div class="panel panel-green">
                      <div class="panel-heading">
                          <div class="row">
                              <div class="col-xs-3">
                                <i class="fa fa-check fa-3x"></i>
                              </div>
                              <div class="col-xs-9 text-right">
                                  <div class="huge">
                                    <% @yearly.each do |pr| %>
                                      <%= pr.actual %>
                                    <% end %>
                                  </div>
                                  <div>Actual</div>
                              </div>
                          </div>
                      </div>
                  </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                      <div class="panel-heading">
                          <div class="row">
                              <div class="col-xs-3">
                                <i class="fa fa-chevron-up fa-3x"></i>
                              </div>
                              <div class="col-xs-9 text-right">
                                <div class="huge">
                                 <% @yearly.each do |pr| %>
                                 <%= pr.progress %>
                                 <% end %>
                                 % 
                                </div>
                                <div>Progress</div>
                              </div>
                          </div>
                      </div>
                    </div>
                </div>
                </div>
                </div>
            </div>

app/views/charts/_detail_board.html.erb
<div class="col-lg-6" style="width: 101%;">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title" style="text-align: center;">Summary</h3>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <!-- Nav tabs -->
      <ul class="nav nav-pills">
        <li class="active"><a href="#home-pills" data-toggle="tab">Day-wise</a></li>
        <li><a href="#ds-pills" data-toggle="tab">Device and Shift-wise</a></li>
        <li><a href="#sp-pills" data-toggle="tab">Shift and Part-wise</a></li>
        <li><a href="#settings-pills" data-toggle="tab">Weekly</a></li>
        <li><a href="#profile-pills" data-toggle="tab">Monthly</a></li>
        <li><a href="#messages-pills" data-toggle="tab">Yearly</a></li>
       </ul>
        <div class="tab-content">
            <div class="tab-pane fade in active" id="home-pills">
            <p>
            <table id="day_wise" class="display table table-responsive" cellspacing="0" width="95%">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Day</th>
                  <th>Target</th>
                  <th>Actual</th>
                  <th>Progress %</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                
                <% if @day_wise %>
                  <% @day_wise.each do |date| %>
                  <tr>
                    <td><%= date.dates %></td>
                    <td><%= date.day_name %></td>
                    <td><%= date.target %></td>
                    <td><%= date.actual %></td>
                    <td><%= date.progress %></td>
                  <% end %>
                  </tr> 
                <% end %>
                
              </tbody>
            </table>

            <br>
            </p>
        </div>
        <div class="tab-pane fade" id="ds-pills">
          <p>
            <table id="ds_wise" class="display table" cellspacing="0" width="95%">
            <span id ="ds" style="float: right;margin-bottom: 10px;"><%= link_to chart_download_report_path('ds', format: "csv"), class: 'btn btn-success'  do %>
              <i class="fa fa-download"></i>
            <% end %></span>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Day</th>
                  <th>WorkBench</th>
                  <th>Shift</th>
                  <th>Count</th>
                  <th>Target</th>
                  <th>Duration</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% if @ds_wise %>
                  <% @ds_wise.each do |date| %>
                  <tr>
                    <td><%= date.dates %></td>
                    <td><%= date.day_name %></td>
                    <td><%= date.workbench %></td>
                    <td><%= date.shift %></td>
                    <td><%= date.count %></td>
                    <td><%= date.target %></td>
                    <td><%= date.duration %></td>
                  <% end %>
                  </tr> 
                <% end %>
                
              </tbody>
            </table>
            <br>
            </p>
        </div>
        <div class="tab-pane fade" id="sp-pills">
          <p>
            <table id="sp_wise" class="display table" cellspacing="0" width="95%">
            <span id ="sp" style="float: right;margin-bottom: 10px;"><%= link_to chart_download_report_path('sp', format: "csv"), class: 'btn btn-success'  do %>
              <i class="fa fa-download"></i>
            <% end %></span>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Shift</th>
                  <th>Workbench</th>
                  <th>Part Number</th>
                  <th>Duration</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% if @sp_wise %>
                  <% @sp_wise.each do |date| %>
                  <tr>
                    <td><%= date.dates %></td>
                    <td><%= date.shift %></td>
                    <td><%= date.workbench %></td>
                    <td><%= date.part_number %></td>
                    <td><%= date.duration %></td>
                  <% end %>
                  </tr> 
                <% end %>
              </tbody>
            </table>
            <br>
            </p>
        </div>
        <div class="tab-pane fade" id="profile-pills">
          <p>
            <table id="day_wise" class="display table" cellspacing="0" width="95%">
              <thead>
                <tr>
                  <th>Month</th>
                  <th>Target</th>
                  <th>Actual</th>
                  <th>Progress % </th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                
                <% if @monthly %>
                  <% @monthly.each do |date| %>
                  <tr>
                    <td><%= date.month_name %></td>
                    <td><%= date.target %></td>
                    <td><%= date.actual %></td>
                    <td><%= number_with_precision(date.progress) %></td>
                  <% end %>
                  </tr> 
                <% end %>
                
              </tbody>
            </table>
            <br>
          </p>
        </div>
        <div class="tab-pane fade" id="messages-pills">
          <p>
            <table id="day_wise" class="display table" cellspacing="0" width="95%">
              <thead>
                <tr>
                  <th>Year</th>
                  <th>Target</th>
                  <th>Actual</th>
                  <th>Progress %</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                
                <% if @yearly %>
                  <% @yearly.each do |date| %>
                  <tr>
                    <td><%= date.year_name %></td>
                    <td><%= date.target %></td>
                    <td><%= date.actual %></td>
                    <td><%= date.progress %></td>
                  <% end %>
                  </tr> 
                <% end %>
                
              </tbody>
            </table>
            <br>
          </p>
        </div>
        <div class="tab-pane fade" id="settings-pills">
          <p>
            <table id="day_wise" class="display table" cellspacing="0" width="95%">
              <thead>
                <tr>
                  <th>Week No.</th>
                  <th>Date.</th>
                  <th>Day</th>
                  <th>Target</th>
                  <th>Actual</th>
                  <th>Progress % </th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% if @weekly %>
                  <% @weekly.each do |date| %>
                  <tr>
                    <td><%= date.week_no %></td>
                    <td><%= date.dates %></td>
                    <td><%= date.day_name %></td>
                    <td><%= date.target %></td>
                    <td><%= date.actual %></td>
                    <td><%= date.progress %></td>
                  <% end %>
                  </tr> 
                <% end %>
              </tbody>
            </table>
            <br>
          </p>
        </div>
      </div>
    </div>
  </div>

app/views/charts/_form.html.erb
<%= form_for(@chart) do |f| %>
  <% if @chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chart.errors.count, "error") %> prohibited this chart from being saved:</h2>

      <ul>
      <% @chart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charts/_leader_board.html.erb
<%= render 'time_update' %>
<!--/.col-lg-6 -->
<div class="col-lg-6" style="width: 101%;">
	<div class="panel panel-success">
		<div class="panel-heading" style="border-color: #5cb85c;color: white;background-color: #5cb85c;"><h3 class="panel-title" style="text-align: center;">LEADER BOARD</h3></div>
			<br>	<!-- /.panel-heading -->
	<div class="row">
		<div class="col-md-6">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h5 class="panel-title" style="text-align: center;">Employee VS Completed</h5>
				</div>
				<div class="panel-body">
					<table id="lb_cmp-pills" class="display table table-striped" cellspacing="0" width="95%">
						<thead>
							<tr>
								<th>Employee Name</th>
								<th>WorkBench</th>
								<th>Part Code</th>
								<th>Parts Completed</th>
								<th>Rank</th>
								<th colspan="3"></th>
							</tr>
						</thead>
						<tbody>
							<% if @lb_result_cmp %>
								<% @lb_result_cmp.each do |date| %>
								<tr>
									<td><%= date.employee_name %></td>
									<td><%= date.workbench_number %></td>
									<td><%= date.part_number %></td>
									<td><%= date.count %></td>
									<td><%= date.row_number %></td>
								<% end %>
								</tr> 
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h5 class="panel-title" style="text-align: center;">Employee VS Running</h5>
				</div>
				<div class="panel-body">
					<table id="lb_pro-pills" class="display table table-striped" cellspacing="0" width="95%">
						<thead>
							<tr>
								<th>Employee Name</th>
								<th>WorkBench</th>
								<th>Part Code</th>
								<th>Target</th>
								<th>Parts Running</th>
								<th colspan="3"></th>
							</tr>
						</thead>
						<tbody>
							<% if @lb_result_pro %>
								<% @lb_result_pro.each do |date| %>
								<tr>
									<td><%= date.employee_name %></td>
									<td><%= date.workbench_number %></td>
									<td><%= date.part_number %></td>
									<td><%= date.target %></td>
									<td><%= date.count %></td>
								<% end %>
								</tr> 
							<% end %>
						</tbody>
					</table>
				</div>
		</div>
	</div>
	</div>
	</div>

app/views/charts/_time_update.html.erb
<div class="timer" style="float: right;width: 495px;">
  <div class="row">
    <div class="col-xs-9 text-right" style="width: 97%;">
      <div class="huge" style="font-size: 30px;">
        <div id="ruby_time" style="float: right;font-weight: bold;color: #093f88;">
          <%= (Time.zone.now).strftime("%d-%m-%Y %I:%M %p") %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/charts/edit.html.erb
<h1>Editing Chart</h1>

<%= render 'form' %>

<%= link_to 'Show', @chart %> |
<%= link_to 'Back', charts_path %>

app/views/charts/index.html.erb
<% content_for :panel_heading do %>Analytics
<% end %>
<%= render 'boards' %>
<%= render 'leader_board' %>
<%= render 'detail_board' %>

<div style="height: 400px; margin: 0 auto">
  <div id="container-speed" style="width: 300px; height: 200px; float: left"></div>
  <div id="container-rpm" style="width: 300px; height: 200px; float: left"></div>
</div>

<script type="text/javascript">

$(document).ready(function() {
      $('#day_wise').DataTable({ responsive: true, ordering: true });
      $('#ds_wise').DataTable({ responsive: true, ordering: true });
      $('#sp_wise').DataTable({ responsive: true, ordering: true });

      setInterval( function () {
        $("#lb_cmp-pills").load(location.href + " #lb_cmp-pills");
        $("#lb_pro-pills").load(location.href + " #lb_pro-pills");
      }, 5000 );
    });

      setInterval( function () {
        $("#ruby_time").load(location.href + " #ruby_time");
        console.log('reloaded'); 
        
      }, 60000 );

  var gaugeOptions = {

    chart: {
        type: 'solidgauge'
    },

    title: 'WorkBench',

    pane: {
        center: ['50%', '85%'],
        size: '140%',
        startAngle: -90,
        endAngle: 90,
        background: {
            backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || '#EEE',
            innerRadius: '60%',
            outerRadius: '100%',
            shape: 'arc'
        }
    },

    tooltip: {
        enabled: false
    },

    // the value axis
    yAxis: {
        stops: [
            [0.1, '#55BF3B'], // green
            [0.5, '#DDDF0D'], // yellow
            [0.9, '#DF5353'] // red
        ],
        lineWidth: 0,
        minorTickInterval: null,
        tickAmount: 2,
        title: {
            y: -70
        },
        labels: {
            y: 15
        }
    },

    plotOptions: {
        solidgauge: {
            dataLabels: {
                y: 5,
                borderWidth: 0,
                useHTML: true
            }
        }
    }
};

// The speed gauge
var chartSpeed = Highcharts.chart('container-speed', Highcharts.merge(gaugeOptions, {
    yAxis: {
        min: 0,
        max: '<%= @data_for_1[1] %>',
        title: {
            text: 'WorkBench No. 1'
        }
    },

    credits: {
        enabled: false
    },

    series: [{
        name: 'Speed',
        data: [<%= @data_for_1[0] %>],
        dataLabels: {
            format: '<div style="text-align:center"><span style="font-size:25px;color:' +
                ((Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black') + '">{y}</span><br/>' +
                   '<span style="font-size:12px;color:silver">No. of Parts</span></div>'
        },
        tooltip: {
            valueSuffix: 'No. of Parts'
        }
    }]

}));

// The RPM gauge
var chartRpm = Highcharts.chart('container-rpm', Highcharts.merge(gaugeOptions, {
    yAxis: {
        min: 0,
        max: '<%= @data_for_2[1] %>',
        title: {
            text: 'WorkBench No. 2'
        }
    },

    series: [{
        name: 'RPM',
        data: [<%= @data_for_2[0] %>] || [0],
        dataLabels: {
            format: '<div style="text-align:center"><span style="font-size:25px;color:' +
                ((Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black') + '">{y}</span><br/>' +
                   '<span style="font-size:12px;color:silver">No. of Parts</span></div>'
        },
        tooltip: {
            valueSuffix: ' revolutions/min'
        }
    }]

}));

// The RPM gauge
var chartRpm1 = Highcharts.chart('container-rpm1', Highcharts.merge(gaugeOptions, {
    yAxis: {
        min: 0,
        max: '<%= @data_for_1[1] %>',
        title: {
            text: 'WorkBench No. 3'
        }
    },

    series: [{
        name: 'RPM',
        data: [<%= @data_for_1[0] %>],
        dataLabels: {
            format: '<div style="text-align:center"><span style="font-size:25px;color:' +
                ((Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black') + '">{y}</span><br/>' +
                   '<span style="font-size:12px;color:silver">No. of Parts</span></div>'
        },
        tooltip: {
            valueSuffix: ' revolutions/min'
        }
    }]

}));
</script>

app/views/charts/new.html.erb
<h1>New Chart</h1>

<%= render 'form' %>

<%= link_to 'Back', charts_path %>

app/views/charts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @chart.name %>
</p>

<%= link_to 'Edit', edit_chart_path(@chart) %> |
<%= link_to 'Back', charts_path %>