config/routes.rb
Rails.application.routes.draw do
  resources :weight_calculators
  resources :charts do
    get :download_report
  end
  resources :trackers

  scope :ujs, defaults: { format: :ujs } do
    patch 'wt_totals' => 'weight_calculators#totals'
    patch 'thing_totals' => 'trackers#totals'
  end
  post 'search' => 'trackers#search'
  resources :import  do
    collection do
      post :import
      post :parts
    end
  end
  resources :iot_data do
      get :process_start
      get :download_report
    
    collection do
      post :import
    end
  end
  
  devise_for :users, only: :session, path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :users, only: [:show]
  root to: 'visitors#index'
end

app/models/tracker.rb
require 'csv'
class Tracker < ActiveRecord::Base
	belongs_to :IotDatum
	belongs_to :charts

	def self.to_csv(options = {})
		desired_columns = ["wb_id", "part_code", "employee_id", "shift", "device_id", "count", "target", "datetime"]
    CSV.generate(options) do |csv|
      csv << desired_columns
      all.each do |product|
        csv << product.attributes.values_at(*desired_columns)
      end
    end
  end
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  skip_before_filter :authenticate_user!
  before_action :set_tracker, only: [:show, :edit, :update, :destroy]

  # GET /trackers
  # GET /trackers.json
  def index
    @trackers = Tracker.all
  end

  # GET /trackers/1
  # GET /trackers/1.json
  def show
    # render js: "alert('The number is: #{params[:id]}')"
  end

  def new
    @tracker = Tracker.new
  end

  def search
    @track_filter = Tracker.select("wb_id, part_code, employee_id, shift, device_id, count, target, to_char(created_at,'yyyy-mm-dd HH12:MI:SS') as datetime").where("to_char(created_at,'yyyy-mm-dd') >= ? and to_char(created_at,'yyyy-mm-dd') <= ?", params[:created_at],params[:updated_at]).order(:part_code)
    respond_to do |format|
      format.csv { send_data @track_filter.to_csv, filename: 'tracker_report.csv' }
    end


  end

  # GET /trackers/1/edit
  def edit
  end

  # POST /trackers
  # POST /trackers.json
  def create
    @tracker = Tracker.new(tracker_params)

    respond_to do |format|
      if @tracker.save
        format.html { redirect_to @tracker, notice: 'Tracker was successfully created.' }
        format.json { render :show, status: :created, location: @tracker }
      else
        format.html { render :new }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackers/1
  # PATCH/PUT /trackers/1.json
  def update
    respond_to do |format|
      if @tracker.update(tracker_params)
        format.html { redirect_to @tracker, notice: 'Tracker was successfully updated.' }
        format.json { render :show, status: :ok, location: @tracker }
      else
        format.html { render :edit }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackers/1
  # DELETE /trackers/1.json
  def destroy
    @tracker.destroy
    respond_to do |format|
      format.html { redirect_to trackers_url, notice: 'Tracker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracker
      @tracker = Tracker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tracker_params
      params.require(:tracker).permit(:wb_id, :part_code, :employee_id, :shift, :device_id, :count, :created_at, :updated_at)
    end
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/views/trackers/_daterange.html.erb
<div class="container">
  <div class='col-md-5' style="width: 23.666667%;">
    <div class="form-group">
      <%= form_tag search_path(filename: 'trackers.csv', format: "csv") do %>
        From Date: <div class='input-group date' id='datetimepicker6'>
        <input id="fromdate" type='text' value="" name="created_at" class="form-control" data-behavior="datepicker">
        
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
        </span>
        </div><br>
        To Date: <div class='input-group date' id='datetimepicker7'>
        <input id="todate" type='text' value="" name="updated_at" class="form-control" data-behavior="datepicker">
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
        </span>
        </div><br>
       <span><%= submit_tag 'Download Tracker', class: 'btn btn-success btn-lg' %></span>
      <% end %>         
      </div>
    </div>
  </div>
</div> 


<script type="text/javascript">
  $(document).ready(function(){
    $('#datepicker').datepicker();
    $('#datetimepicker6').datepicker({
    format: "yyyy-mm-dd"
      });
    $('#datetimepicker7').datepicker({
    format: "yyyy-mm-dd"
      });
  });

</script>

app/views/trackers/_form.html.erb
<%= form_for(@tracker) do |f| %>
  <% if @tracker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tracker.errors.count, "error") %> prohibited this tracker from being saved:</h2>

      <ul>
      <% @tracker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wb_id %><br>
    <%= f.number_field :wb_id %>
  </div>
  <div class="field">
    <%= f.label :part_code %><br>
    <%= f.text_field :part_code %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.number_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :shift %><br>
    <%= f.number_field :shift %>
  </div>
  <div class="field">
    <%= f.label :device_id %><br>
    <%= f.number_field :device_id %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trackers/_show.html.erb
Now you don't!

app/views/trackers/edit.html.erb
<h1>Editing Tracker</h1>

<%= render 'form' %>

<%= link_to 'Show', @tracker %> |
<%= link_to 'Back', trackers_path %>

app/views/trackers/index.html.erb
<% content_for(:page_header) do %>
<% end %>
<%= render 'daterange' %>
<% content_for :panel_heading do %>Data Summary<% end %>
<p id="notice"><%= notice %></p>

<table id="iott" class="display table" cellspacing="0" width="80%">
  <thead>
    <tr>
      <th>Wb</th>
      <th>Part code</th>
      <th>Employee</th>
      <th>Shift</th>
      <th>Device</th>
      <th>Count</th>
      <th>Created Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trackers.each do |tracker| %>
      <tr>
        <td><%= tracker.wb_id %></td>
        <td><%= tracker.part_code %></td>
        <td><%= tracker.employee_id %></td>
        <td><%= tracker.shift %></td>
        <td><%= tracker.device_id %></td>
        <td><%= tracker.count %></td>
        <td><%= (tracker.created_at).strftime("%d/%m/%Y %I:%M:%S %p") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<% content_for(:extra_scripts) do %>
  
  <script type="text/javascript">
    $(document).ready(function() {
      $('#iott').DataTable({ responsive: true });
    });

    $('#datepicker .input-daterange').datepicker({
    });

    $(".dashboard-totals").click();
  </script>
<% end %>

app/views/trackers/new.html.erb
<h1>New Tracker</h1>

<%= render 'form' %>

<%= link_to 'Back', trackers_path %>

app/views/trackers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wb:</strong>
  <%= @tracker.wb_id %>
</p>

<p>
  <strong>Part code:</strong>
  <%= @tracker.part_code %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @tracker.employee_id %>
</p>

<p>
  <strong>Shift:</strong>
  <%= @tracker.shift %>
</p>

<p>
  <strong>Device:</strong>
  <%= @tracker.device_id %>
</p>

<p>
  <strong>Count:</strong>
  <%= @tracker.count %>
</p>

<%= link_to 'Edit', edit_tracker_path(@tracker) %> |
<%= link_to 'Back', trackers_path %>

app/views/trackers/show.js.erb
$("#target-for-change").html("<%= j render(partial: 'show') %>");