config/routes.rb
Rails.application.routes.draw do
  resources :weight_calculators
  resources :charts do
    get :download_report
  end
  resources :trackers

  scope :ujs, defaults: { format: :ujs } do
    patch 'wt_totals' => 'weight_calculators#totals'
    patch 'thing_totals' => 'trackers#totals'
  end
  post 'search' => 'trackers#search'
  resources :import  do
    collection do
      post :import
      post :parts
    end
  end
  resources :iot_data do
      get :process_start
      get :download_report
    
    collection do
      post :import
    end
  end
  
  devise_for :users, only: :session, path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :users, only: [:show]
  root to: 'visitors#index'
end

app/views/layouts/_boards.html.erb
<!-- /.row -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-eye fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= @active_devices.count if @active_devices %></div>
                                    <div>Active Workbench</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-check fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= @completed_parts.count if @completed_parts %></div>
                                    <div>Completed Parts</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-refresh fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= @processing_parts.count if @processing_parts %></div>
                                    <div>Processing Parts</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-eye-slash fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= @inactive_devices.count if @inactive_devices %></div>
                                    <div>Inactive Devices</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-primary navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= image_tag 'tvslsl_logo.png', class: "img-responsive center-block", :alt => "avatar", :style => 'height: 53px;'%>
  </div>

  <div class="navbar-primary sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav in" id="side-menu">
        <li>
          <a href="/iot_data">
            <i class="fa fa-dashboard fa-fw"></i>
            Dashboard</a>
        </li>
        <li>
          <a href="#"><i class="fa fa-th-list fa-fw"></i>Menu<span class="fa arrow"></span></a>
          <ul class="nav nav-second-level collapse">
            <li>
              <%= link_to '<i class="fa fa-video-camera fa-fw" aria-hidden="true"></i> Workbench Planner</a>'.html_safe, iot_data_path() %>
            </li>
            <li>
              <%= link_to '<i class="fa fa-bar-chart-o fa-fw"></i> Analytics</a>'.html_safe, charts_path() %>
            </li>
            <li>
              <%= link_to '<i class="fa fa-upload fa-fw" aria-hidden="true"></i> Masters Upload</a>'.html_safe, import_index_path() %>
            </li>
            <li>
              <%= link_to '<i class="fa fa-tasks fa-fw"></i> Trackers</a>'.html_safe, trackers_path() %>
            </li>
            <li>
              <%= link_to '<i class="fa fa-credit-card fa-fw"></i> Weight Calculator</a>'.html_safe, weight_calculators_path() %>
            </li>
            <li>
            <a href="/">
            <i class="fa fa-info-circle fa-fw"></i>
            About</a>
          </li>
          <% if user_signed_in? %>
            <li class="divider"></li>
            <li>
              <%= link_to '<i class="fa fa-sign-out fa-fw"></i>Logout</a>'.html_safe, destroy_user_session_path, :method=>'delete' %>
            </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_title.html.erb
<div class="row">
  <div class="col-lg-12">
  	<h3 class="page-header" style="font-family: sans-serif;font-weight: bold;color: #093f88;text-align: -webkit-center;"><%= content_for?(:page_header) ? yield(:page_header) : "Intelligent Counting System" %></h3>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-127162600-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-127162600-1');
    </script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <%= content_for?(:title) ? yield(:title) : "Intelligent Counting System" %>
  </title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Intelligent Counting System" %>">

  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag 'application', "chartkick" %>
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <script src="https://code.highcharts.com/highcharts-more.js"></script>
  <script src="https://code.highcharts.com/modules/solid-gauge.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="wrapper" class="">
    <%= render 'layouts/navbar' %>
  </div>

  <div id="page-wrapper" style="min-height: 2500px;">
    <%= render 'layouts/title' %>
    <%= render 'layouts/messages' %>
    <div>
      <div class="panel panel-info">
        <div class="panel-heading" style="color: #074e71;background-color: #99cee8;font-weight: bold;">
          <%= content_for?(:panel_heading) ? yield(:panel_heading) : "Dashboard" %>
        </div>
        <div class="panel-body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</body>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= content_for?(:extra_scripts) ? yield(:extra_scripts) : nil %>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <div class="background_image">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <%= content_for?(:title) ? yield(:title) : "Intelligent Counting System" %>
  </title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : " Intelligent Counting System " %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body style="background-color: white;">
  <div class="container">
    <div class="row"><br><br><br><br>
      <div class="col-md-4 col-md-offset-4" style="text-align:center;">
        <%= image_tag 'tvslsl_logo4.jpg', class: "img-responsive center-block", :style => "height: 75px;", :alt => "avatar" %><br><br>
        <h1 style="font-family: sans-serif;font-weight: bold;color: #093f88;text-align: -webkit-center;font-size: x-large;">Intelligent Counting System</h1>
      </div>

    </div>

    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Please Sign In</h3>
          </div>
          <div class="panel-body">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</html>